// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function ExpandConcept(arg1) {
  return window['go']['main']['App']['ExpandConcept'](arg1);
}

export function GenerateImagePrompt(arg1, arg2) {
  return window['go']['main']['App']['GenerateImagePrompt'](arg1, arg2);
}

export function GenerateLyrics(arg1, arg2) {
  return window['go']['main']['App']['GenerateLyrics'](arg1, arg2);
}

export function GenerateSetlist(arg1) {
  return window['go']['main']['App']['GenerateSetlist'](arg1);
}

export function GenerateSunoPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSunoPrompt'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHWID() {
  return window['go']['main']['App']['GetHWID']();
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetShortHWID() {
  return window['go']['main']['App']['GetShortHWID']();
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function ValidateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ValidateAPIKey'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
