// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {license} from '../models';
import {generator} from '../models';
import {config} from '../models';

export function ActivateLicense(arg1:string):Promise<license.AppStatus>;

export function ExpandConcept(arg1:generator.AlbumInput):Promise<generator.AlbumConcept>;

export function GenerateImagePrompt(arg1:generator.AlbumConcept,arg2:Array<generator.Track>):Promise<generator.ImagePromptResult>;

export function GenerateLyrics(arg1:generator.AlbumConcept,arg2:generator.Track):Promise<generator.LyricsResult>;

export function GenerateSetlist(arg1:generator.AlbumConcept):Promise<generator.SetlistResult>;

export function GenerateSunoPrompt(arg1:generator.AlbumConcept,arg2:generator.Track,arg3:string):Promise<generator.SunoPromptResult>;

export function GetConfig():Promise<config.Config>;

export function GetHWID():Promise<string>;

export function GetLicenseStatus():Promise<license.AppStatus>;

export function GetShortHWID():Promise<string>;

export function HasAPIKey():Promise<boolean>;

export function MkdirAll(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SelectDirectoryDialog():Promise<string>;

export function ValidateAPIKey(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
